version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_local
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestion_app
    depends_on:
      - postgres
    env_file:
      - .env
    command: python3 ingestion.py
    volumes:
      - ./data_test:/app/data
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
